### ISSUE TITLE
response to PLOS comp bio reviews task list

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/manuscript.ICIKendallTau#12]
This is a task list of what @rmflight thinks needs to be done after this review. It will likely get added to and modified after meeting with @hunter-moseley and @psbhatt, but this is a first stab at grouping the issues and making sure they are collected together and don't get missed.

- Reorganize overall flow of manuscript:
   - [ ] 1st result is sensitivity to missingness
     - [ ] Fold Fig 2 into Fig 3
   - [ ] 2nd is detecting outliers
     - [ ] Need to create a fully synthetic RNA-seq dataset with real outliers for this
  - [ ] 3rd is performance & subsampling

1. Show the left-censored problem exists in real datasets
   - [ ] Show for RNA-seq.
   - [ ] Show for metabolomics.

2. Better comparison with Pearson and Kendall and itself with missingness.
   * <strike>Reviewer 1 complains about whether higher correlation with left-censored distribution is perhaps not intuitive. This means we didn't explain what was going on well enough, and maybe tried to do too much in a single figure.</strike>
   - [ ] fix comparisons in Figure 2 and Figure 3, or add something else to make it clearer ...

3. Better demonstration of how bioinformaticians benefit from this new measure.
   - This goes back to **1** as well, and **2**, and then of course bringing up more about outliers in the introduction and showing they can be a real problem.
   - [ ] cite Gierlinski et al on outliers.
   - [ ] more text on outlier problem, which it seems we missed in the introduction.

4. Clarify how outliers are determined.
   - Rev 2 (and 3 I think) didn't see that we are using boxplot.stats to decide outliers, which uses 1.5 * IQR (I think).
   - [ ] Verify how boxplot.stats determines outliers.
   - [ ] Explicitly state how we decide outliers so it's harder to miss.
   - [ ] Perhaps a new measure for outlierniess: 
      - [ ] Median correlations, then take median absolute deviation of those median sample correlations, divide by median of medians, and things > 0.05 are possibly outliers
   
5. Ground truth outliers.
   - One issue reviewers seemed to also have was with having a dataset where we had **known** outliers that we could judge things against. One way to address this is via simulation.
   - [ ] examine [this paper](https://academic.oup.com/bioinformatics/article/31/17/2778/183245) as a way to do simulation, and then maybe perturb some samples in it, maybe via low sequencing, more errors in priming ...
   - [ ] we could also try just making some samples that are definite outliers due to mixes up in the ordering of feature measures ...
   - [ ] Can we treat a subset of Gierlinski samples as **definite** known outliers, due to the coverage issues they found?

6. Better explanation of ICI-Kt algorithm.
   > If the missing values are assumed to be below the detection limit but greater than 0 (for those actually recorded as 0), then there are several cases where the definition is questionable. Take the example of the 8 concordant cases on page 8 (labelled 1-8 in that order): cases 3-8 all require the qualification that the observed are greater than 0, which excludes the situations where there are (excess of) observed zeros in many RNA-seq data. 
   - Both Rev 2 and Rev 3 seem to misunderstand the Kendall-tau algorithm in general, or rather our explanation of it. Perhaps we could add something graphical to help?
   - [ ] More explanation of ICI-Kt.

7. Explain that we are not actually doing imputation.
   - [ ] Acknowledge imputation literature (which I thought we did).
   - [ ] Explain that we are not really doing imputation.

Minor things:
   - [ ] fix the 2nd to last concordant definition.
   - [ ] while we are at it, can we improve the spacing in those equations so they are easier to parse?
   - [x] should we remove the instrument response in Figure 1?
